---
author:
  - 'Justin Davis, C<< <juster at cpan dot org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.87_01
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-AUR
no_index:
  dir:
    - ex
  directory:
    - inc
    - t
    - xt
  package:
    - WWW::AUR::RPC
    - WWW::AUR::UserAgent
requires:
  Archive::Tar: 0
  Carp: 0
  Cwd: 0
  Fcntl: 0
  File::Path: 2.06
  File::Spec: 0
  HTTP::Cookies: 0
  JSON: 0
  LWP::Protocol::https: 6
  LWP::UserAgent: 6
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/juster/perl-www-aur
version: 0.12
